kensho-technologies/eslint-config

- index.js
We already allow non-ID-linked `<label>`s, but we do so by [disabling a deprecated rule](https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/label-has-for.md#deprecated-label-has-for). We can either continue to allow it outright (including `<label>`s that do not contain an `<input>`) or we use the 'jsx-a11y/label-has-associated-control' rule to enforce that either a `<label>` wraps an `<input>` or is ID-linked.
Thoughts?
//cc @billyjanitsch
> Allow non-id-linked labels

- index.js
I didn't use the right word in #29 😬
https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/b800f40a2a69ad48015ae9226fbe879f946757ed/src/rules/label-has-associated-control.js#L28
//cc @billyjanitsch
> Fix label-has-associated-control rule config

- javascript.js
Was chatting with Paavan yesterday and we agreed that enforcing sort order of non-lifecycle methods was more annoying than useful.
> Loosen component sort order

- __snapshots__/test.js.snap
- javascript.js
- package-lock.json
- package.json
~Currently using an alpha version of the TypeScript parser/plugin to test ESLint 6 compatibility, but I'd like to wait for a stable release before merging. Looks like that should happen [relatively soon](https://github.com/typescript-eslint/typescript-eslint/issues/501#issuecomment-519983992).~ 🦋
> Upgrade upstream config and plugins to ESLint 6

- __snapshots__/test.js.snap
- fixtures/jsdoc.ts
- index.js
- package-lock.json
- package.json
This ensures that JSDoc comments, when they exist, are well-formatted. Specifically, that they have a sentence-form description, document their parameters and return value, and use reasonable indentation.
We could require a JSDoc comment on all functions/classes/methods by default, but we're far away from this at the moment so I'm not sure if it's a useful rule to enable. Projects can always enable it manually if they'd like to strive for this.
> Lint JSDoc comments

- index.js
This allows:
```ts
function foo() {}
const bar = () => {}
```
(Previously we had to include a comment. But I don't think the lack of clarity has been a problem for us in practice.)
> Permit noop functions in TS

- .prettierrc.json
- README.md
- index.js
- package-lock.json
- package.json
In favor of using Prettier directly, so as to format non-JS/TS files.
> Remove Prettier plugin and associated rule

- README.md
- package-lock.json
- package.json
Closes #26.
npm@7 installs peer dependencies automatically, which makes it significantly less inconvenient for all of these to be peer deps. Consumers don't have to use npm@7; they can always install the peer deps manually.
> Move plugins/parsers to peer dependencies

- .github/workflows/ci.yml
- index.js
- jest-resolver.js
- jest.config.js
- package-lock.json
- package.json
The new major release of the upstream Airbnb config has enabled some [new](https://github.com/airbnb/javascript/commit/1bc8cabd447ef9ce69d27ae70e67eb47daeffc21) [rules](https://github.com/airbnb/javascript/commit/f3d3a075cda2acc02011e71991c10bb5b4a15278). I've followed the usual strategy:
1. Release a major version that includes most of these changes. (This PR.)
2. Loosen things as needed in subsequent minor releases.
The new Airbnb config release technically supports ESLint 7, but I added 8 as an explicit peer dep to give us more flexibility with rule changes.
This PR also includes a bit of CI cleanup and a workaround for Jest's lack of package `exports` resolution, which ESLint 8 now uses.
> Upgrade dependencies and require ESLint 8

- index.js
The rule (correctly) errors on this code, but this workaround is necessary in TypeScript because function components must return `JSX.Element | null` to do a fundamental limitation in the current TS compiler.
```tsx
function Foo(): JSX.Element {
return <>foo</>
}
```
The rule does have [an option to support expressions](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-useless-fragment.md#allowexpressions) but that requires wrapping all non-elements in variables which seems inconvenient. Useless fragments aren't really a problem so it seems easier to disable the rule.
> Loosen `react/jsx-no-useless-fragment`

- index.js
See [the docs](https://github.com/typescript-eslint/typescript-eslint/blob/84b4a8c5a67bc8da586cb00589fd56737a261885/packages/eslint-plugin/docs/rules/default-param-last.md). This permits optional parameters after parameters with defaults, e.g.:
```ts
function(foo: number, bar = 1, baz?: number) {}
```
> Override `default-param-last` with TypeScript equivalent

- __snapshots__/test.js.snap
- fixtures/variables.ts
- index.js
These used to be checked by the TS compiler, but now they'll be checked by the linter instead. https://github.com/kensho-technologies/tsconfig/pull/7 is the corresponding PR to our TS config.
> Disallow unused variables and parameters

- __snapshots__/test.js.snap
- fixtures/functionComponent.tsx
- index.js
This allows for the following pattern of omitting certain properties from an object:
```ts
const {foo, ...rest} = obj
doSomething(rest)
```
> Permit unused rest siblings

- __snapshots__/test.js.snap
- fixtures/syntax.tsx
- index.js
The AirBnB config's justification for disallowing this syntax is that it requires a generator polyfill, but this is no longer true as we stopped supporting IE 11.
> Permit `for...of` statements

- __snapshots__/test.js.snap
- index.js
In practice, this is one of our most frequently-disabled rules because it prevents files that will eventually have multiple exports (e.g., `utils.ts`, `env.ts`) from being structured that way when there is initially only a single export.
> Permit files to have a single named export

- __snapshots__/test.js.snap
- index.js
This is checked by the TypeScript compiler.
> Disable `import/no-unresolved` in TypeScript

- __snapshots__/test.js.snap
- index.js
- package-lock.json
- package.json
Closes https://github.com/kensho-technologies/eslint-config/issues/70.
This causes the linter to trigger various deprecation warnings due to the transitive issue mentioned in https://github.com/kensho-technologies/eslint-config/issues/70, but that issue has been open for a year without much movement on the associated PR. At this point, it's not worth continuing to block several minor version upgrades of TypeScript, so let's make do with the deprecation warnings for now.
> Upgrade dependencies

- __snapshots__/test.js.snap
- index.js
- package-lock.json
- package.json
ESLint's base parser should now be sufficient for our needs, particularly because our codebases are now overwhelmingly TS aside from the occasional config file.
> Remove Babel parser

- README.md
- index.js
- package-lock.json
- package.json
A first step towards refreshing our config. This inlines all of the rules that we were using from `eslint-config-airbnb` and removes the dependency. The result is a bit of a mess, but it's non-disruptive (doesn't enable any rules that were previously disabled) and now it's much clearer which rules are enabled. We can work on paring things down from here.
> Remove dependency on Airbnb config

- .github/workflows/ci.yml
- package-lock.json
- package.json
Removes support for Node 18 now that there are no internal uses.
> Require Node >=20.9

- index.js
- package-lock.json
- package.json
- tests/__snapshots__/config.test.ts.snap
- tests/fixtures/react-query.tsx
This adds [TanStack Query's ESLint plugin](https://tanstack.com/query/latest/docs/eslint/eslint-plugin-query) and its recommended config, primarily to guard against missing `queryKey` values as shown in the new test fixture.
> Add TanStack Query plugin
